# Generated by Django 5.0.6 on 2024-06-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resources', models.FileField(upload_to='resources')),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
