# Generated by Django 5.0.6 on 2024-06-08 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.course')),
            ],
            options={
                'db_table': 'Learning',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.course')),
            ],
            options={
                'db_table': 'Requirements',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.course')),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
    ]
