# Generated by Django 5.0.6 on 2024-06-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_learning_requirements_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
