# Generated by Django 5.0.4 on 2024-06-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_id',
            field=models.CharField(max_length=100),
        ),
    ]
