# Generated by Django 5.0.4 on 2024-06-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_usercourse_payment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='Payment',
        ),
        migrations.AlterModelTable(
            name='usercourse',
            table='Usercourse',
        ),
    ]
