# Generated by Django 5.0.4 on 2024-06-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_payment_table_alter_usercourse_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
