# Generated by Django 5.0.6 on 2024-06-30 16:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
